[phases.setup]
nixPkgs = ["nodejs_20", "npm_9"]

[phases.install]
cmds = ["cd vibethead-frontend", "npm ci"]

[phases.build]
cmds = ["cd vibethead-frontend", "npm run build"]

[start]
cmd = "cd vibethead-frontend && NODE_ENV=production npm start"
